[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.7"
optimizer = true
optimizer_runs = 10000
gas_reports = ['*']
etherscan_api_key="4WSWEEHUBEMDB85A9SWF3N3SZ9FN7MWSVD"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config